import Foundation
import SwiftData

/// Mirror of `RecurringExpenseMaterializer` for incoming money. Generates either
/// `Transaction(.income)` rows (auto, for reliable incomes like salary on direct deposit)
/// or `Receivable` rows (manual confirmation, when the user wants to confirm receipt).
enum RecurringIncomeMaterializer {

    static let defaultHorizon: TimeInterval = 35 * 24 * 60 * 60

    static func materializeAll(
        context: ModelContext,
        now: Date = .now,
        calendar: Calendar = .current
    ) {
        let horizon = now.addingTimeInterval(defaultHorizon)
        let descriptor = FetchDescriptor<RecurringIncome>(
            predicate: #Predicate<RecurringIncome> { !$0.isPaused }
        )
        guard let rules = try? context.fetch(descriptor) else { return }
        for rule in rules {
            materialize(rule: rule, horizon: horizon, context: context, calendar: calendar)
        }
    }

    static func materialize(
        rule: RecurringIncome,
        horizon: Date,
        context: ModelContext,
        calendar: Calendar = .current
    ) {
        guard !rule.isPaused else { return }

        let limit = min(horizon, rule.endDate ?? .distantFuture)
        let existingTxnKeys = Set(rule.transactions.map { monthKey(for: $0.occurredOn, calendar: calendar) })
        let existingReceivableKeys = Set(rule.receivables.map { monthKey(for: $0.expectedDate, calendar: calendar) })

        var cursor = startOfMonth(for: rule.startDate, calendar: calendar)
        let limitMonth = startOfMonth(for: limit, calendar: calendar)

        while cursor <= limitMonth {
            let key = monthKey(for: cursor, calendar: calendar)
            let alreadyMaterialized = rule.requiresConfirmation
                ? existingReceivableKeys.contains(key)
                : existingTxnKeys.contains(key)

            if !alreadyMaterialized {
                if let occurrence = occurrenceDate(forMonthAnchor: cursor, day: rule.dayOfMonth, calendar: calendar),
                   occurrence <= limit {
                    let note = rule.note.isEmpty ? rule.name : rule.note
                    if rule.requiresConfirmation {
                        let receivable = Receivable(
                            name: rule.name,
                            amount: rule.amount,
                            expectedDate: occurrence,
                            note: note,
                            status: .pending,
                            category: rule.category,
                            account: rule.account
                        )
                        receivable.recurringIncomeSource = rule
                        context.insert(receivable)
                        Task { @MainActor in ReceivableNotifications.schedule(for: receivable) }
                    } else {
                        let txn = Transaction(
                            amount: rule.amount,
                            kind: .income,
                            occurredOn: occurrence,
                            note: note,
                            category: rule.category,
                            account: rule.account
                        )
                        txn.recurringIncomeSource = rule
                        context.insert(txn)
                    }
                }
            }
            guard let next = calendar.date(byAdding: .month, value: 1, to: cursor) else { break }
            cursor = next
        }
    }

    /// Removes future, not-yet-realized occurrences (occurredOn > now) for a rule.
    /// Covers both Transactions and pending Receivables generated by the rule.
    /// Past Transactions and received Receivables are kept so the user's history stays intact.
    static func deleteUnrealizedOccurrences(
        rule: RecurringIncome,
        context: ModelContext,
        now: Date = .now
    ) {
        for txn in rule.transactions where txn.occurredOn > now {
            context.delete(txn)
        }
        for receivable in rule.receivables where receivable.isPending && receivable.expectedDate > now {
            Task { @MainActor [receivable] in ReceivableNotifications.cancel(for: receivable) }
            context.delete(receivable)
        }
    }

    /// Propagates the rule's current fields into existing pending Receivables (past + future)
    /// and unrealized Transactions (future only). Occurrences whose month falls outside
    /// the rule's window are removed. Past received Receivables and realized Transactions
    /// are left untouched. Use this when editing a rule WITHOUT changing `requiresConfirmation`.
    static func syncPending(
        rule: RecurringIncome,
        context: ModelContext,
        now: Date = .now,
        calendar: Calendar = .current
    ) {
        let startMonth = startOfMonth(for: rule.startDate, calendar: calendar)
        let endMonth = rule.endDate.map { startOfMonth(for: $0, calendar: calendar) }
        let resolvedNote = rule.note.isEmpty ? rule.name : rule.note

        for receivable in rule.receivables where receivable.isPending {
            let receivableMonth = startOfMonth(for: receivable.expectedDate, calendar: calendar)
            if receivableMonth < startMonth || (endMonth.map { receivableMonth > $0 } ?? false) {
                Task { @MainActor [receivable] in ReceivableNotifications.cancel(for: receivable) }
                context.delete(receivable)
                continue
            }
            receivable.name = rule.name
            receivable.amount = rule.amount
            receivable.category = rule.category
            receivable.account = rule.account
            receivable.note = resolvedNote
            if let newDate = occurrenceDate(forMonthAnchor: receivableMonth, day: rule.dayOfMonth, calendar: calendar) {
                receivable.expectedDate = newDate
            }
            Task { @MainActor [receivable] in ReceivableNotifications.schedule(for: receivable) }
        }

        for txn in rule.transactions where txn.occurredOn > now {
            let txnMonth = startOfMonth(for: txn.occurredOn, calendar: calendar)
            if txnMonth < startMonth || (endMonth.map { txnMonth > $0 } ?? false) {
                context.delete(txn)
                continue
            }
            txn.amount = rule.amount
            txn.category = rule.category
            txn.account = rule.account
            txn.note = resolvedNote
            if let newDate = occurrenceDate(forMonthAnchor: txnMonth, day: rule.dayOfMonth, calendar: calendar) {
                txn.occurredOn = newDate
            }
        }
    }

    // MARK: - Helpers

    private static func monthKey(for date: Date, calendar: Calendar) -> String {
        let components = calendar.dateComponents([.year, .month], from: date)
        return "\(components.year ?? 0)-\(components.month ?? 0)"
    }

    private static func startOfMonth(for date: Date, calendar: Calendar) -> Date {
        let components = calendar.dateComponents([.year, .month], from: date)
        return calendar.date(from: components) ?? date
    }

    private static func occurrenceDate(forMonthAnchor anchor: Date, day: Int, calendar: Calendar) -> Date? {
        let range = calendar.range(of: .day, in: .month, for: anchor) ?? 1..<29
        let lastDay = range.upperBound - 1
        let clampedDay = max(1, min(day, lastDay))
        var components = calendar.dateComponents([.year, .month], from: anchor)
        components.day = clampedDay
        guard let date = calendar.date(from: components) else { return nil }
        return calendar.startOfDay(for: date)
    }
}
