import Foundation
import SwiftData

/// Idempotently materializes future occurrences of `RecurringExpense` rules as
/// real `Transaction` rows up to `horizon`. Safe to call on app launch, on rule
/// edit, or when navigating to a future month.
enum RecurringExpenseMaterializer {

    /// Default horizon: 35 days ahead. Enough to cover the current month plus a buffer
    /// so the "Previsto neste mês" tile picks up upcoming fixed expenses early.
    static let defaultHorizon: TimeInterval = 35 * 24 * 60 * 60

    static func materializeAll(
        context: ModelContext,
        now: Date = .now,
        calendar: Calendar = .current
    ) {
        let horizon = now.addingTimeInterval(defaultHorizon)
        let descriptor = FetchDescriptor<RecurringExpense>(
            predicate: #Predicate<RecurringExpense> { !$0.isPaused }
        )
        guard let rules = try? context.fetch(descriptor) else { return }
        for rule in rules {
            materialize(rule: rule, horizon: horizon, context: context, calendar: calendar)
        }
    }

    static func materialize(
        rule: RecurringExpense,
        horizon: Date,
        context: ModelContext,
        calendar: Calendar = .current
    ) {
        guard !rule.isPaused else { return }

        let limit = min(horizon, rule.endDate ?? .distantFuture)
        let existingTxnKeys = Set(rule.transactions.map { monthKey(for: $0.occurredOn, calendar: calendar) })
        let existingBillKeys = Set(rule.bills.map { monthKey(for: $0.dueDate, calendar: calendar) })

        var cursor = startOfMonth(for: rule.startDate, calendar: calendar)
        let limitMonth = startOfMonth(for: limit, calendar: calendar)

        while cursor <= limitMonth {
            let key = monthKey(for: cursor, calendar: calendar)
            let alreadyMaterialized = rule.requiresConfirmation
                ? existingBillKeys.contains(key)
                : existingTxnKeys.contains(key)

            if !alreadyMaterialized {
                if let occurrence = occurrenceDate(forMonthAnchor: cursor, day: rule.dayOfMonth, calendar: calendar),
                   occurrence <= limit {
                    let note = rule.note.isEmpty ? rule.name : rule.note
                    if rule.requiresConfirmation {
                        let bill = Bill(
                            name: rule.name,
                            amount: rule.amount,
                            dueDate: occurrence,
                            note: note,
                            status: .pending,
                            category: rule.category,
                            account: rule.account,
                            recurringSource: rule
                        )
                        context.insert(bill)
                        Task { @MainActor in BillNotifications.schedule(for: bill) }
                    } else {
                        let txn = Transaction(
                            amount: rule.amount,
                            kind: .expense,
                            occurredOn: occurrence,
                            note: note,
                            category: rule.category,
                            account: rule.account
                        )
                        txn.recurringSource = rule
                        context.insert(txn)
                    }
                }
            }
            guard let next = calendar.date(byAdding: .month, value: 1, to: cursor) else { break }
            cursor = next
        }
    }

    /// Removes future, not-yet-realized occurrences (occurredOn > now) for a rule.
    /// Covers both Transactions and pending Bills generated by the rule.
    /// Past Transactions and paid Bills are kept so the user's history stays intact.
    static func deleteUnrealizedOccurrences(
        rule: RecurringExpense,
        context: ModelContext,
        now: Date = .now
    ) {
        for txn in rule.transactions where txn.occurredOn > now {
            context.delete(txn)
        }
        for bill in rule.bills where bill.isPending && bill.dueDate > now {
            Task { @MainActor [bill] in BillNotifications.cancel(for: bill) }
            context.delete(bill)
        }
    }

    // MARK: - Helpers

    private static func monthKey(for date: Date, calendar: Calendar) -> String {
        let components = calendar.dateComponents([.year, .month], from: date)
        return "\(components.year ?? 0)-\(components.month ?? 0)"
    }

    private static func startOfMonth(for date: Date, calendar: Calendar) -> Date {
        let components = calendar.dateComponents([.year, .month], from: date)
        return calendar.date(from: components) ?? date
    }

    /// Returns a date at the requested day of month, clamped to the month's last day.
    private static func occurrenceDate(forMonthAnchor anchor: Date, day: Int, calendar: Calendar) -> Date? {
        let range = calendar.range(of: .day, in: .month, for: anchor) ?? 1..<29
        let lastDay = range.upperBound - 1
        let clampedDay = max(1, min(day, lastDay))
        var components = calendar.dateComponents([.year, .month], from: anchor)
        components.day = clampedDay
        guard let date = calendar.date(from: components) else { return nil }
        return calendar.startOfDay(for: date)
    }
}
